{
    'name': 'Flex CRM Custom',
    'version': '17.0.0.0',
    'summary': 'Add Demand Request to CRM',
    'description': 'Add Demand Request to CRM',
    'category': '',
    'author': 'Sohaib Alamleh||Flex-ops',
    'website': 'https://www.flexops.com',
    'license': '',
    'depends': ['base', 'crm', 'crm_iap_enrich', 'contacts', 'account','mail'],
    'data': [
        'security/ir.model.access.csv',
        'security/groups.xml',
        'data/email_notifiy.xml',
        'views/crm_lead.xml',
        'views/division_manager.xml',
        'wizard/lead_opp.xml',
        'views/res_users.xml',
        'security/ir.rules.xml',
    ],
    'demo': [''],
    'installable': True,
    'auto_install': False,
}
